sudo: required

services:
  - docker

script:
  - docker build -t tf .
  - docker run -d --name pg kiasaki/alpine-postgres
  - docker run -d --name tb --link pg:postgres beevelop/taiga-back:alpine
  - docker run --name tf --link tb:taigaback -d tf
  - docker exec tf /bin/sh -c "apk add --no-cache curl && curl -f localhost:80"
  - docker logs tf
