#!/bin/bash

set -ea # Exit on Error and Export all vars

if [ -n "$DEBUG_ENTRYPOINT" ]; then
  set -x
fi

. /opt/conf.env

envsubst < conf.json > taiga-front-dist/dist/conf.json
envsubst < upstream.conf > /etc/nginx/upstream.conf

nginx -g "daemon off;"
